version: '3.9'

services:
  backend:
    image: plumxeun98/backend:${DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
  frontend:
    image: plumxeun98/frontend:${DOCKER_IMAGE_TAG}
    ports:
      - "3000:3000"