name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Docker Last Day git action build
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew docker buildDocker
